const actions = {
    TOGGLE_THEME: 'TOGGLE_THEME',
    IS_AUTHENTICATED: 'IS_AUTHENTICATED',
    REGISTER_USER: 'REGISTER_USER',
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER'
}

export default actions
