export const LIGHT_THEME = 'light'
export const DARK_THEME = 'dark'
export const SLIDER_LIGHT = 'https://i.ibb.co/7JfqXxB/sunny.png'
export const SLIDER_DARK = 'https://i.ibb.co/FxzBYR9/night.png'
export const PROFILE_PICTURE = 'https://icon-library.com/images/no-profile-picture-icon/no-profile-picture-icon-2.jpg'
